
name: TypeScript CI

on:
  push:
    branches: [ website ]
  pull_request:
    branches: [ website ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
        with:
          name: wbkc-wrapper-website-${{ github.sha }}
          path: |
            build/